### ISSUE TITLE
Missed keys when finetuning with the given pretained weight 

### ISSUE THREAD

**Issue by xupp1989** [saic-violet/bilayer-model#5]
Hello,

I have a problem when finetuning on the dataset of the voxceleb2 with the given pretained weight.

untimeError: Error(s) in loading state_dict for NetworkWrapper:
	Missing key(s) in state_dict: "frequencies".
	size mismatch for net.mlp.0.weight_orig: copying a param with shape torch.Size([256, 136]) from checkpoint, the shape in current model is torch.Size([256, 1088]).
	size mismatch for net.mlp.0.weight_v: copying a param with shape torch.Size([136]) from checkpoint, the shape in current model is torch.Size([1088]).

**Comment by egorzakharov** [comment]
Hello! Seems like the number of facial landmarks in your dataset is larger than 68 landmarks which we used for training, is that correct? In that case, you can exclude keypoints_embedder from the list of init_networks. It will be initialized and trained from scratch, while the rest of the models will have their checkpoints loaded.

**Comment by xupp1989** [comment]
Thanks! I have solved this problem by setting the parameter 'pse_use_harmonic_enc' as False.

**Comment by NTU-P04922004** [comment]
Hi @xupp1989,

May I know how you fine-tune the pretrained weight?
Do you use the provided scripts (for example, train_base_model_8gpus.sh) to fine-tune?
