### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by nagadit** [saic-violet/bilayer-model#6]
how did you launch this on your mobile phone?  conversion to onnx?  or how ?

**Comment by egorzakharov** [comment]
Hello!

We used PyTorch Mobile for the base model (forward functions had to be rewritten into traceable formats) and the enhancer. The guiding gradients that are input to the enhancer were calculated manually.

For the inference, we did a separate conversion of the inference generator into ONNX and then SNPE. It also requires a custom forward function, and grid_sampling operation should coded manually in the mobile app.

**Comment by nagadit** [comment]
How did you coded grid_sampling? example?
what language did you use for coded grid_sampling? C++ or Java?

**Comment by egorzakharov** [comment]
Here is an official PyTorch implementation, we also used is as a reference

https://github.com/pytorch/pytorch/blob/33519e19abfe99747ee654df61b83d3c82f03c27/aten/src/ATen/native/GridSampler.cpp

**Comment by egorzakharov** [comment]
ATen version:

https://github.com/pytorch/pytorch/blob/8f37ad82907a8d28268256965dfd36792a326878/aten/src/ATen/native/cpu/GridSamplerKernel.cpp

**Comment by nagadit** [comment]
you used it from libtorch library, i thought you wrote it in pure c++

using this library is very expensive in memory for the sake of one function

**Comment by egorzakharov** [comment]
We used the implementation from the first link. If you take a look closely, it does not have any external dependencies and can be copy-pasted.

I am closing this issue, but feel free to reopen it if you feel like it has not been resolved

**Comment by jfun9494** [comment]
@egorzakharov did you port the grid_sample operation with User-Defined Operation (UDO) in SNPE? Can you share the code for it?
